name: 🧪 Integration Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published, edited, prereleased]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: 🐍 Run pytest
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
    - name: 📰 Checkout repo
      uses: actions/checkout@v6

    - name: 😎 Setup uv
      uses: astral-sh/setup-uv@v7

    - name: 🧪 Run tests
      run: uv run pytest

  lint:
    name: 👕 Lint
    uses: WGBH-MLA/.github/.github/workflows/lint.yml@main

  black:
    name: 🖤 Black
    uses: WGBH-MLA/.github/.github/workflows/black.yml@main
